correction script pass

diff --git a/scripts/pass b/scripts/pass
--- a/scripts/pass
+++ b/scripts/pass
@@ -17,12 +17,12 @@ if [ ! -f list ];then
 else
 	LIST="list"
 fi
-for i in `cat $LIST`
+for NAME in `cat $LIST`
 do
    BUILD="yes"
    PKGMK="pkgmk.passes"
-   if [ -f ${LOG}/$i.log ]; then
-      if ( grep "^=======>" ${LOG}/$i.log|grep "succeeded"  > /dev/null);then
+   if [ -f ${LOG}/$NAME.log ]; then
+      if ( grep "^=======>" ${LOG}/$NAME.log|grep "succeeded"  > /dev/null);then
          BUILD="no"
       else
          BUILD="yes"
@@ -30,18 +30,18 @@ do
 
    fi
    if [ "$BUILD" == "yes" ]; then
+      cd $NAME
       if [ "$PASS" == "chroot" ]; then
-           cd ${i}
+	PKGMK="pkgmk.passes"
       else
-         cd ${i}@*
+        PKGMK="pkgmk"
       fi
-      NAME=`echo $i|cut -d "@" -f1`
       if [ "$NAME" != "kernel" ];then
-      	$PKGMK -cf ../../../bin/pkgmk.conf.passes -i -kw 2>&1|tee ${LOG}/$i.log || exit 1
+      	$PKGMK -cf ../../../bin/pkgmk.conf.passes -i -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
       else
         $PKGMK -d -cf ../../../bin/pkgmk.conf.passes -i -kw
       fi
-      if ( grep "^=======>" ${LOG}/$i.log| tail -1 |grep "ERROR"  > /dev/null);then
+      if ( grep "^=======>" ${LOG}/$NAME.log| tail -1 |grep "ERROR"  > /dev/null);then
          exit 1
       fi
       cd ..
